### ISSUE TITLE
Pokemon Sapphire hangs at the end of the intro.

### ISSUE THREAD

**Issue by fleroviux** [jsmolka/eggvance#4]
![image](https://user-images.githubusercontent.com/13669774/87096772-d7f55b80-c243-11ea-8ab2-69d5eb955bc1.png)

Tested with a japanese ROM and a 1.1 USA ROM. In both cases the game will hang at the end of the intro scene.

**Comment by jsmolka** [comment]
This is caused by the bundled replacement BIOS. Everything is fine with the real one.

**Comment by fleroviux** [comment]
Doesn't happen in NBA or mGBA with the same BIOS.

**Comment by jsmolka** [comment]
Weird. The only thing I could think of is a wrongly initialized register.

**Comment by jsmolka** [comment]
This turns out to be a pretty interesting issue. I was able to find the infinite loop thanks to the pokemon disassembly project. Turns out that there is a null pointer dereference in [this function](https://github.com/pret/pokeruby/blob/master/src/fieldmap.c#L87) which results in a bios read (it's described really well in the comment). The bug has been [fixed](https://github.com/pret/pokeemerald/blob/master/src/fieldmap.c#L114) in Emerald, that's why I never noticed it.

Now I just have to find out why the cached BIOS value is garbage ¯\\\_(ツ)_/¯

**Comment by jsmolka** [comment]
Fixed improving bad reads https://github.com/jsmolka/eggvance/commit/213c7ab0a18502125b725536c433da3bf90d0b84.

**Comment by fleroviux** [comment]
Neat. Your DMA open bus isn't quite right yet, though. Successful 16-bit reads should mirror the value in the MSW of the `bus` register. If I recall correctly the game Lufia relies on this in the intro.

**Comment by jsmolka** [comment]
I will look into it, thank you.
