### ISSUE TITLE
Attribute NanoboyAdvance

### ISSUE THREAD

**Issue by fleroviux** [jsmolka/eggvance#6]
It always seemed to me that eggvance has taken strong inspiration from NanoboyAdvance from the get go.
The latest case, the RTC implementation, is a clear case to me. The code is pretty much the exact same except for some minor naming and style differences and fewer comments. It follows the exact same structure and logic.

NanoboyAdvance:
https://github.com/fleroviux/NanoboyAdvance/blob/master/source/emulator/cartridge/gpio/rtc.cpp

eggvance:
https://github.com/jsmolka/eggvance/blob/d925e80d3cc11ca043fbdc896524fba787a3226b/eggvance/src/gamepak/rtc.cpp

In the past I've looked over this because a) NanoboyAdvance was credited to some extent in the README (while now any credit is gone) and b) it was less clear cut that some code is a direct copy of mine instead of merely being inspired.

Therefore I kindly ask to add proper attribution.

**Comment by jsmolka** [comment]
Sorry about that. The credits got lost while I was cleaning up the readme. I didn't want to be disrespectful. The main influences of my emulator have been GBE+ in the very early and NanoboyAdvance for the later stages.

I am quite embarrassed by the RTC situation because I wasted most of my weekend on it without properly understanding it. I had a half working version on a local branch but instead of throwing it away and doing it all over I decided to take your code. I wanted to revisit it this week, fully understand it and make my own thing.

**Comment by fleroviux** [comment]
I'm glad this is settled now and that the lack of attribution was merely an error from reworking the README.
I remember spending quite a bit of time to make it work too. The documentation on GBATEK can be a bit unclear at times, at least if you're unfamiliar with electrical engineering lingo, such as the dash in `/SCK` meaning that it is active low. That the RTC code in some Pokémon ROM-Hacks only works in VisualBoyAdvance, because the pin direction is messed up didn't help either.
Seeing that it was copied so blatantly while attribution also was removed therefore made me a bit upset.
